# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chiffre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_chiffre', models.CharField(max_length=100, verbose_name=b'Chiffre + unit\xc3\xa9 (\xe2\x82\xac,$,%...)')),
                ('data_baseline', models.CharField(max_length=60, verbose_name=b'baseline du Chiffre')),
            ],
        ),
        migrations.CreateModel(
            name='ContactRevue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identite', models.CharField(max_length=250)),
                ('intitule_fonction', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=28, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revue',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('couverture', models.ImageField(help_text=b'Taille recommand\xc3\xa9e : 300px de large; Poids maximal recommand\xc3\xa9 : 80 Ko ', upload_to='/home/patsykakaz/ACDV/MAIN/static/media/couvertures', verbose_name=b'Couverture de la revue')),
                ('type_revue', models.CharField(choices=[(b'magazine', b'magazine'), (b'magazine grand format', b'magazine grand format'), (b'journal', b'journal'), (b'carnet format poche', b'carnet format poche'), (b'lettre professionnelle', b'lettre professionnelle')], max_length=250, verbose_name=b'Type de revue')),
                ('format_revue', models.CharField(max_length=250, verbose_name=b'Format de la revue')),
                ('periodicite', models.CharField(max_length=250, verbose_name=b'P\xc3\xa9riode de la revue')),
                ('tirage', models.IntegerField(verbose_name=b'Tirage de la revue (entrez un nombre)')),
                ('pagination', models.IntegerField(verbose_name=b'Pagination moyenne (entrez un nombre)')),
                ('lectorat', models.CharField(max_length=250, verbose_name=b'Description du lectorat')),
                ('baseline', models.CharField(max_length=300, verbose_name=b'Baseline de la revue')),
                ('presentation', models.TextField(verbose_name=b'Pr\xc3\xa9sentation de la revue')),
                ('site_web', models.URLField(blank=True, default=b'', help_text=b'Effacez la valeur "False" en l\'absence d\'URL', null=True, verbose_name=b'site web')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='Univers',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('small_cover', models.ImageField(help_text=b'Taille recommand\xc3\xa9e: 800x450; Poinds maximal recommand\xc3\xa9: 90 Ko', upload_to='/home/patsykakaz/ACDV/MAIN/static/media/univers/small_cover', verbose_name=b"Image repr\xc3\xa9sentant l'univers sur la page d'accueil")),
                ('full_cover', models.ImageField(help_text=b'Taille recommand\xc3\xa9e: 1600px de large; Poids maximal recommand\xc3\xa9: 180Ko', upload_to='/home/patsykakaz/ACDV/MAIN/static/media/univers/full_cover', verbose_name=b"Image repr\xc3\xa9sentant l'univers sur la page Univers")),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
        migrations.AddField(
            model_name='revue',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.Univers', verbose_name=b'Fili\xc3\xa8re de la revue'),
        ),
        migrations.AddField(
            model_name='contactrevue',
            name='revue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.Revue'),
        ),
        migrations.AddField(
            model_name='chiffre',
            name='univers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.Univers'),
        ),
    ]
